-- 코드를 입력하세요
WITH TOP AS 
(SELECT M.MEMBER_ID
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY 1
ORDER BY COUNT(1) DESC
LIMIT 1)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW R INNER JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID, TOP
WHERE R.MEMBER_ID = TOP.MEMBER_ID
ORDER BY 3, 2
