-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR.CAR_TYPE = '세단'
AND MONTH(HIS.START_DATE) = 10
ORDER BY 1 DESC